//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_G6_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long IdBitacora { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string MensajeError { get; set; }
        public string Origen { get; set; }
        public long IdUsuario { get; set; }
        public string DireccionIP { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
